const boardActions = {
    CREATE_BOARD : 'CREATE_BOARD',
    UPDATE_BOARD : 'UPDATE_BOARD',
    DELETE_BOARD : 'DELETE_BOARD',
    ADD_LIST_ID_TO_A_BOARD : 'ADD_LIST_ID_TO_A_BOARD',
    ADD_Task_ID_TO_A_BOARD: 'ADD_Task_ID_TO_A_BOARD',
    DELETE_LIST_ID_FROM_A_BOARD : 'DELETE_LIST_ID_FROM_A_BOARD',
    DELETE_TASK_ID_FROM_A_BOARD : 'DELETE_TASK_ID_FROM_A_BOARD'
}

export default boardActions